/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: ed95f40ed51564393dac535dce3ceffb)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	DB: D1Database;
	NEXT_TAG_CACHE_D1: D1Database;
	ASSETS: Fetcher;
	DATABASE_DRIVER: "d1";
	DATABASE_AUTO_INIT: "false";
	DATABASE_CACHE_NAMESPACE: "d1:shortly-db";
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./.open-next/worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_DRIVER" | "DATABASE_AUTO_INIT" | "DATABASE_CACHE_NAMESPACE">> {}
}
