import { beforeAll, beforeEach, describe, expect, it, mock } from "bun:test"
import { NextRequest } from "next/server"

type RoutePost = (typeof import("./route"))["POST"]
type RouteOptions = (typeof import("./route"))["OPTIONS"]

type ApiAuthResult =
  | { error: string }
  | {
      data: {
        id: string
        userId: string
      }
    }

type AllowedEmailDomain = {
  host: string
  minLocalPartLength: number
} | null

type CreateMailboxResult =
  | {
      data: {
        id: string
        emailAddress: string
        localPart: string
        domain: string
        createdAt: Date
      }
    }
  | {
      error: string
      status: 400 | 409 | 429
    }

let POST: RoutePost
let OPTIONS: RouteOptions

let initDbCalls = 0
let apiAuthResult: ApiAuthResult = {
  data: {
    id: "key_123",
    userId: "user_123",
  },
}
let allowedEmailDomain: AllowedEmailDomain = {
  host: "signup.l",
  minLocalPartLength: 1,
}
let generatedPrefixes: string[] = ["alice-smith001"]
let createMailboxResults: CreateMailboxResult[] = []
let createMailboxInputs: Array<{
  userId: string
  emailAddress: string
  hourlyCreateLimit?: number
}> = []
let touchedApiKeys: Array<{ id: string; userId: string }> = []

mock.module("@/lib/db", () => ({
  initDb: async () => {
    initDbCalls += 1
  },
}))

mock.module("@/lib/api-auth", () => ({
  requireApiKeyUser: async () => apiAuthResult,
  touchApiKeyUsage: async (id: string, userId: string) => {
    touchedApiKeys.push({ id, userId })
  },
}))

mock.module("@/lib/random-email-prefix", () => ({
  generateRandomEmailPrefix: () => generatedPrefixes.shift() || "fallback-user001",
}))

mock.module("@/lib/site-domains", () => ({
  getAllowedEmailDomain: async () => allowedEmailDomain,
}))

mock.module("@/lib/site-settings", () => ({
  getSiteSettings: async () => ({
    userMaxLinksPerHour: 12,
  }),
}))

mock.module("@/lib/temp-email", () => ({
  createTempMailboxForUser: async (
    userId: string,
    emailAddress: string,
    options?: { hourlyCreateLimit?: number }
  ) => {
    createMailboxInputs.push({
      userId,
      emailAddress,
      hourlyCreateLimit: options?.hourlyCreateLimit,
    })

    const configuredResult = createMailboxResults.shift()
    if (configuredResult) {
      return configuredResult
    }

    const [localPart, domain] = emailAddress.split("@")
    return {
      data: {
        id: "mailbox_123",
        emailAddress,
        localPart,
        domain,
        createdAt: new Date("2026-04-19T12:00:00.000Z"),
      },
    }
  },
}))

function createRequest(body: unknown) {
  return new NextRequest("https://shortly.test/api/v1/aliases", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: "Bearer sk_shortly_test_key",
      "x-requested-with": "XMLHttpRequest",
    },
    body: typeof body === "string" ? body : JSON.stringify(body),
  })
}

beforeAll(async () => {
  ;({ POST, OPTIONS } = await import("./route"))
})

beforeEach(() => {
  initDbCalls = 0
  apiAuthResult = {
    data: {
      id: "key_123",
      userId: "user_123",
    },
  }
  allowedEmailDomain = {
    host: "signup.l",
    minLocalPartLength: 1,
  }
  generatedPrefixes = ["alice-smith001"]
  createMailboxResults = []
  createMailboxInputs = []
  touchedApiKeys = []
})

describe("addy.io compatible alias route", () => {
  it("responds to cors preflight requests", () => {
    const response = OPTIONS()

    expect(response.status).toBe(204)
    expect(response.headers.get("access-control-allow-origin")).toBe("*")
    expect(response.headers.get("access-control-allow-methods")).toContain("POST")
    expect(response.headers.get("access-control-allow-headers")).toContain("Authorization")
  })

  it("returns 401 when api key auth fails", async () => {
    apiAuthResult = { error: "Unauthorized" }

    const response = await POST(createRequest({ domain: "signup.l" }))

    expect(response.status).toBe(401)
    await expect(response.json()).resolves.toEqual({
      message: "Unauthorized",
    })
    expect(initDbCalls).toBe(1)
    expect(createMailboxInputs).toHaveLength(0)
    expect(touchedApiKeys).toHaveLength(0)
  })

  it("returns 422 when domain is missing", async () => {
    const response = await POST(createRequest({ description: "Generated by Bitwarden." }))

    expect(response.status).toBe(422)
    await expect(response.json()).resolves.toEqual({
      message: "The domain field is required.",
      errors: {
        domain: ["The domain field is required."],
      },
    })
    expect(createMailboxInputs).toHaveLength(0)
  })

  it("returns 403 when the requested email domain is not enabled", async () => {
    allowedEmailDomain = null

    const response = await POST(createRequest({ domain: "gmail.com" }))

    expect(response.status).toBe(403)
    await expect(response.json()).resolves.toEqual({
      message: "This email domain is not enabled.",
      errors: {
        domain: ["This email domain is not enabled."],
      },
    })
    expect(createMailboxInputs).toHaveLength(0)
  })

  it("creates a temp mailbox and returns addy.io response shape", async () => {
    const response = await POST(
      createRequest({
        domain: "signup.l",
        description: "Website: example.com. Generated by Bitwarden.",
      })
    )
    const body = await response.json()

    expect(response.status).toBe(201)
    expect(createMailboxInputs).toHaveLength(1)
    expect(createMailboxInputs[0].userId).toBe("user_123")
    expect(createMailboxInputs[0].emailAddress).toBe("alice-smith001@signup.l")
    expect(createMailboxInputs[0].hourlyCreateLimit).toBe(12)
    expect(body).toEqual({
      data: {
        id: "mailbox_123",
        user_id: "user_123",
        local_part: createMailboxInputs[0].emailAddress.split("@")[0],
        domain: "signup.l",
        email: createMailboxInputs[0].emailAddress,
        active: true,
      },
    })
    expect(touchedApiKeys).toEqual([{ id: "key_123", userId: "user_123" }])
  })

  it("retries generated aliases when a local part collides", async () => {
    generatedPrefixes = ["taken-prefix001", "fresh-prefix001"]
    createMailboxResults = [
      { error: "This email address already exists", status: 409 },
    ]

    const response = await POST(createRequest({ domain: "signup.l" }))

    expect(response.status).toBe(201)
    expect(createMailboxInputs).toHaveLength(2)
    expect(createMailboxInputs[0].emailAddress).toBe("taken-prefix001@signup.l")
    expect(createMailboxInputs[1].emailAddress).toBe("fresh-prefix001@signup.l")
    expect(touchedApiKeys).toEqual([{ id: "key_123", userId: "user_123" }])
  })

  it("rejects domains whose minimum local-part length cannot be met without modifying the generated prefix", async () => {
    allowedEmailDomain = {
      host: "signup.l",
      minLocalPartLength: 64,
    }

    const response = await POST(createRequest({ domain: "signup.l" }))

    expect(response.status).toBe(400)
    await expect(response.json()).resolves.toEqual({
      message: "This email domain cannot generate compatible aliases.",
      errors: {
        domain: ["This email domain cannot generate compatible aliases."],
      },
    })
    expect(createMailboxInputs).toHaveLength(0)
    expect(touchedApiKeys).toHaveLength(0)
  })

  it("returns 429 when mailbox creation is rate limited", async () => {
    createMailboxResults = [
      { error: "每小时最多创建 12 个临时邮箱，请稍后再试", status: 429 },
    ]

    const response = await POST(createRequest({ domain: "signup.l" }))

    expect(response.status).toBe(429)
    await expect(response.json()).resolves.toEqual({
      message: "每小时最多创建 12 个临时邮箱，请稍后再试",
    })
    expect(touchedApiKeys).toHaveLength(0)
  })
})
